fullscreen=false
logfile = true
gameName = "Sapphire Machine"
gameDesc = "A reimplementation of Submachine"
windowWidth = 800
windowHeight = 600
referenceWidth = 300
referenceHeight = 300
globalScale = 1

[debug]
debugHot = true
debugNoSound = true
debugMenuEnabled = true
logRaw = true
logLevel = "ERROR"